from turtle import *

def square(size, color):
    turtle.begin_fill()
    turtle.color(color)
    forward(size)
    right(90)
    forward(size)
    right(90)
    forward(size)
    right(90)
    forward(size)
    turtle.end_fill()
square(100, "blue")

def triangle(size, color):
    turtle.begin_fill()
    turtle.color(color)
    forward(size)
    right(120)
    forward(size)
    right(120)
    forward(size)
    turtle.end_fill()
triangle(25, "red")

def pentagon(size, color):
    turtle.begin_fill()
    turtle.color(color)
    forward(size)
    right(72)
    forward(size)
    right(72)
    forward(size)
    right(72)
    forward(size)
    right(72)
    forward(size)
    turtle.end_fill()
pentagon(50, "purple")

def hexagon(size, color):
    turtle.begin_fill()
    turtle.color(color)
    forward(size)
    right(60)
    forward(size)
    right(60)
    forward(size)
    right(60)
    forward(size)
    right(60)
    forward(size)
    right(60)
    forward(size)
    turtle.end_fill()
hexagon(75, "yellow")

def octagon(size, color):
    turtle.begin_fill()
    turtle.color(color)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    right(45)
    forward(size)
    turtle.end_fill()
octagon(80, "orange")

def star(size, color):
    turtle.begin_fill()
    turtle.color(color)
    for i in range(5):
        forward(size)
        right(144)
    turtle.end_fill()
star(155, "green")

def circle(size, color):
    turtle.begin_fill()
    turtle.color(color)
    width(size)
    circle(180)
    turtle.end_fill()
circle(132, "yellow")

